=== codeonym/tech_web_avc/tp5/XSD/index.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="lettera">
    <xs:complexType mixed="true">
      <xs:sequence>
        <xs:element name="cliente" type="xs:string" />
        <xs:element name="ordine">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="articolo" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="cordice" type="xs:positiveInteger" minOccurs="1" maxOccurs="1" />
                    <xs:element name="desc" type="xs:string" minOccurs="1" maxOccurs="1" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="num" type="xs:positiveInteger" />
          </xs:complexType>
        </xs:element>
        <xs:element name="responsabile">
          <xs:complexType mixed="true">
            <xs:all>
              <xs:element name="tit" type="xs:string" />
            </xs:all>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== codeonym/tech_web_avc/tp5/XSD/index.xml
<?xml version="1.0"?>
<lettera xmlns:xsi="http://www.w3c.org/2001/XMLSchema_instance"
  xsi:schemaLocation="index.xsd"
> gentle <cliente>tttttt</cliente>, eefrfrfrtrttrtr <ordine
    num="1234">
    <articolo>
      <codice>1</codice>
      <desc>articolo 1</desc>
    </articolo>
    <articolo>
      <codice>5</codice>
      <desc>articolo 5</desc>
    </articolo>
  </ordine> dsfdfdfdfdfdfdfdfdfdfdfdfdfdfdf <responsabile><tit>
  dr.</tit>Mario rossi</responsabile>
</lettera>
