=== codeonym/tech_web_avc/tp5/XML/index.dtd
<!ELEMENT results (game*)>
<!ELEMENT game (team+)>
<!ATTLIST game id ID #REQUIRED>
<!ELEMENT team (card|goal)*>
<!ATTLIST team name CDATA #REQUIRED>
<!ATTLIST team play_at_home (yes|no) "no" >
<!ELEMENT card EMPTY>
<!ELEMENT goal EMPTY>
<!ATTLIST card type (yellow|red) #REQUIRED>
<!ATTLIST card player CDATA #REQUIRED>
<!ATTLIST goal player CDATA #REQUIRED>
<!ATTLIST goal penalty (yes|no) "no">
<!ATTLIST goal time CDATA #REQUIRED>

=== codeonym/tech_web_avc/tp5/XML/index.xml
<?xml version="1.0"?>
<!DOCTYPE results SYSTEM "index.dtd">
<results>
  <game id="rff453">
    <team name="howlers" play_at_home="yes">
      <goal player="mark colmann" penalty="yes" time="75:42" />
      <card type="yellow" player="ablerto deminos" />
      <card type="yellow" player="picaso matrins" />
    </team>
    <team name="leakers">
      <card type="yellow" player="uerik delfamos" />
      <card type="red" player="neckolas goodman" />
      <goal player="reco delma" time="15:22" />
      <goal player="eric brownie" time="95:01" />
    </team>
  </game>
  <game id="rff454">
    <team name="howlers" play_at_home="yes">
      <goal player="mark colmann" penalty="yes" time="75:42" />
      <card type="yellow" player="ablerto deminos" />
      <card type="yellow" player="picaso matrins" />
    </team>
    <team name="leakers"/>
  </game>
  <game id="rff455">
    <team name="howlers" play_at_home="yes">
      <goal player="mark colmann" penalty="yes" time="75:42" />
    </team>
    <team name="leakers">
      <card type="red" player="neckolas goodman" />
    </team>
  </game>
  <game id="rff456">
    <team name="howlers" play_at_home="yes">
      <goal player="mark colmann" penalty="yes" time="75:42" />
      <card type="yellow" player="picaso matrins" />
    </team>
    <team name="leakers">
      <goal player="eric brownie" time="95:01" />
    </team>
  </game>
</results>
